### ISSUE TITLE
 missing a file in the out folder

### ISSUE THREAD

**Issue by MrsJLW** [rajarsheem/nslkdd-deep#2]
Thanks for the answer, and one more question: when I ran the program, I found a file missing in the out folder，that is 'new_input.npz'. Can you send full code exchange learning? Thank you very much.

**Comment by rajarsheem** [comment]
That file gets created [here](https://github.com/rajarsheem/nslkdd-deep/blob/master/DA.ipynb) . Check last line of In [59].

**Comment by MrsJLW** [comment]
> That file gets created [here](https://github.com/rajarsheem/nslkdd-deep/blob/master/DA.ipynb) . Check last line of In [59].

Thank you very much

**Comment by rajarsheem** [comment]
You are welcome! Closing this issue.
